extends Node

signal player_position_changed(new_position: Vector2)
signal player_direction_changed(new_direction: Vector2)
signal health_changed(new_health: int, max_health: int)
signal mana_changed(new_mana: int, max_mana: int)
signal experience_gained(amount: int)
signal level_up(new_level: int)
signal item_picked_up(item: Dictionary)
signal item_used(item_id: String)
signal inventory_changed()
signal quest_completed(quest_id: String)
signal quest_updated(quest_id: String, objective: String, progress: int)
signal player_died()
signal map_entered(map_id: String)
signal game_saved()
signal game_loaded()
signal enemy_spawned(enemy: Node)
signal enemy_died(enemy: Node, position: Vector2)
